### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by marin797** [binghuang21/BM-Transformer#1]
请问你怎么解决这个问题的，在fast_transformers中，你是怎么解决
  File "D:\anaconda3\envs\gen_music\lib\site-packages\fast_transformers\attention\causal_linear_attention.py", line 23, in causal_linear
    V_new = causal_dot_product(Q, K, V)
  File "D:\anaconda3\envs\gen_music\lib\site-packages\fast_transformers\causal_product\__init__.py", line 48, in forward
    product
TypeError: 'NoneType' object is not callable
![Uploading Snipaste_2024-06-01_16-52-42.png…]()

**Comment by binghuang21** [comment]
卸载fast_transformers，重新用pip install –user pytorch-fast-transformers 再次尝试安装，可以尝试在pip安装fast_transformer的时候加 --no-cache-dir参数

**Comment by marin797** [comment]
> 卸载fast_transformers，重新用pip install –user pytorch-fast-transformers 再次尝试安装，可以尝试在pip安装fast_transformer的时候加 --no-cache-dir参数

可以分享一下你的cuda和torch版本吗？我用别人的whl文件才安装上的

**Comment by marin797** [comment]
> > 卸载fast_transformers，重新用pip install –user pytorch-fast-transformers 再次尝试安装，可以尝试在pip安装fast_transformer的时候加 --no-cache-dir参数
> 
> 可以分享一下你的cuda和torch版本吗？我用别人的whl文件才安装上的



> 卸载fast_transformers，重新用pip install –user pytorch-fast-transformers 再次尝试安装，可以尝试在pip安装fast_transformer的时候加 --no-cache-dir参数

老哥，加个v吧，我被这问题困了两周了。麻烦加我一下也行15168876029

**Comment by marin797** [comment]
> 卸载fast_transformers，重新用pip install –user pytorch-fast-transformers 再次尝试安装，可以尝试在pip安装fast_transformer的时候加 --no-cache-dir参数

有偿！麻烦您了！！！

**Comment by binghuang21** [comment]
fast-transformers需要在linux环境下安装，windows环境需要在wsl里面装

**Comment by marin797** [comment]
感谢，之前发现了这个问题了！已经解决了发自我的 iPhone在 2024年11月1日，10:11，binghuang21 ***@***.***> 写道：﻿
fast-transformers需要在linux环境下安装，windows环境需要在wsl里面装
